# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = "https://arilerner.github.io"
# Language used
languageCode = "en-us"
# Website title
title = "Ari Lerner"
# Theme used
theme = "hugo-astatine-theme"

publishDir = 'docs' 


preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"


# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """Ari Lerner academic site."""
    # Author of the site
    authorName = "Ari Lerner"
    


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
